<script type="text/javascript">
        var chart;
        $(document).ready(function() {
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'container',
                    margin: [80, 200, 60, 100],
                    zoomType: 'xy',
                    events:
                     {
                        click: function(e)
                        {
                            // find the clicked values and the series
                            var x = e.xAxis[0].value,
                                y = e.yAxis[0].value,
                                series = this.series[0];        
                        }
                    }                    
                },
                credits: {
                	enabled:false
                },
                title: {
                    text: 'Data for XH Gui',
                    style: {
                        margin: '10px 0 0 0' // center it
                    }
                },
                xAxis: [{
                    categories: [<?php echo $dateidsJS;?>],
                    labels: { 
                        formatter: function() {
                            var date = (this.value).split(" ");                            
                            return date[0];
                        },
                        rotation: -45,
                        align: 'right'
                    }
                }],
                yAxis: [{ // Primary yAxis
                    title: {
                        text: 'Wall Time',
                        style: {
                            color: '#AA4643'
                        }
                    },
                    labels: {
                        formatter: function() {
                            return usecToSize(this.value, 2);
                        },
                        style: {
                            color: '#AA4643'
                        }
                    }
                },{ // Secondary yAxis
                    title: {
                        text: 'Peak Memory Usage',
                        style: {
                            color: '#89A54E'
                        }
                    },
                    labels:
                    {   
                        formatter: function() {
                            return bytesToSize(this.value, 2);
                        },
                        style: {
                            color: '#89A54E'
                        }
                    },
                    opposite: true
                },{ // Tertiary yAxis
                    title: {
                        text: 'CPU',
                        style: {
                            color: '#4572A7'
                        }
                    },
                    labels: {
                        formatter: function() {
                            return this.value;
                        },
                        style: {
                            color: '#4572A7'
                        }
                    },
                    opposite: true,
                    offset: 100
                }],
                tooltip: {
                    crosshairs: true,
                    shared:true,
                    formatter: function() {
                        var s = '<b>'+ this.x +'</b>';

                        $.each(this.points, function(i, point) {
                            s+= '<br /><b style="color:' + point.series.color + '">'+ point.series.name +'</b> ';
                            
                            if(point.series.name == 'Peak Memory Usage') {
                                s += bytesToSize(point.y, 2);
                            } else if(point.series.name == 'Wall Time') {
                                s += usecToSize(point.y, 2);
                            } else {
                                s += point.y;
                            }
                        });

                        return s;
                    }
                },
                legend: {
                    verticalAlign: "top",
                    align: "left",
                    borderWidth: 0,
                    y: 30,
                    x: 90,
                    floating: true
                },
                plotOptions: {
                      series: {
                        lineWidth: 1,
                          point: {
                            events: {
                                'click': function() {
                                      
                                      if (this.series.data.length > 1) {
                                        var runid = (this.category).split(" ");
                                        document.location = '?run=' + runid[2];               
                                      }                                   
                                }
                            }
                        }
                    }
                },                     
                series: [{
                    name: 'CPU',
                    color: '#4572A7',
                    type: 'line',
                    yAxis: 2,
                    data: [<?php echo $cpuJS;?>]
                },{
                    name: 'Peak Memory Usage',
                    color: '#89A54E',
                    type: 'line',
                    yAxis: 1,
                    data: [<?php echo $pmuJS;?>]
                },{
                    name: 'Wall Time',
                    color: '#AA4643',
                    type: 'line',
                    data: [<?php echo $wtJS;?>]
                }]
              });
        });
</script>
