<script type="text/javascript">
var chart;
$(document).ready(function() {
    chart = new Highcharts.Chart({
        credits: { enabled: false },
        chart: {
            renderTo: 'container',
            margin: [60, 200, 60, 100],
            events: {
                click: function(e) {
                    // find the clicked values and the series
                    var x = e.xAxis[0].value,
                        y = e.yAxis[0].value,
                        series = this.series[0];
                }
            }
        },
        title: { text: false },
        xAxis: [{
            categories: [<?php echo $dateidsJS;?>],
            labels: {
                formatter: function() {
                    var date = (this.value).split(" ");
                    return date[0];
                },
                rotation: -45,
                align: 'right',
            }
        }],
        yAxis: [{ // Primary yAxis
            labels:
            {
                formatter: function() {
                    return this.value;
                },
                style: {
                    color: '#89A54E'
                }
            },
            title: {
                text: 'Peak Memory Usage',
                style: {
                    color: '#89A54E'
                }
            },
            opposite: true,
        }, { // Secondary yAxis
            title: {
                text: 'CPU',
                style: {
                    color: '#4572A7'
                }
            },
            labels: {
                formatter: function() {
                    return this.value;
                },
                style: {
                    color: '#4572A7'
                }
            }
        }, { // Tertiary yAxis
            title: {
                text: 'Wall Time (ms)',
                style: {
                    color: '#AA4643'
                }
            },
            labels: {
                formatter: function() {
                    return this.value;
                },
                style: {
                    color: '#AA4643'
                }
            },
            opposite: true,
            offset: 100
        }],
        tooltip: {
            formatter: function() {
                var unit = {
                    '': '',
                    '': '',
                    '': ''
                }[this.series.name];

                return '<b>'+ this.series.name +'</b><br/>' + this.y +'';
            },
            crosshairs: true
        },
        legend: {
            style: { top: '10px' },
            borderWidth: 0
        },
        plotOptions: {
              series: {
                lineWidth: 2,
                  point: {
                    events: {
                        'click': function() {
                            if (this.series.data.length > 1) {
                                var runid = (this.category).split(" ");
                                document.location = '?run=' + runid[2];
                            }
                        }
                    }
                }
            }
        },
        series: [{
            name: 'CPU',
            color: '#4572A7',
            yAxis: 1,
            data: [<?php echo $cpuJS;?>],
        },{
            name: 'Wall Time',
            color: '#AA4643',
            yAxis: 2,
            data: [<?php echo $wtJS;?>]
        },{
            name: 'Peak Memory Usage',
            color: '#89A54E',
            data: [<?php echo $pmuJS;?>,]
        }]
      });

});
</script>
