<?php
$runs = array();
foreach ($url_params as $key => $runId) {
	if (strpos($key, 'run') === 0) {
		$runs[$key] = $runId;
		xhprof_array_unset($url_params, $key);
	}
}
$invertedRuns = array();
$count = count($runs);
for ($idx = 1, $invertedIdx = $count; $invertedIdx > 0; $idx++, $invertedIdx--) {
	$invertedRuns['run' . $idx] = $runs['run' . $invertedIdx];
}

print('<div id="view-diff-tables">');
print('<div class="invert">');
print('<a class="invertIcon" href="?' . http_build_query($invertedRuns) . '"><img src="img/invert.png" height="80" width="85" alt="Invert Report" /></a>');
print("<div id=\"link-id\">");

$idx = 0;
foreach($runs as $key => $runId) {
	print('<h2 class="diff-details">' . ucfirst($key) . " ID: $runId against {$xhprof_runs_impl->run_details[$idx]['server name']}</h2>");
	$idx++;
}
print("</div>");
print("</div>");

print('<div id="diff-graph">');
print('<a href="callgraph.php?' . http_build_query($runs) . '" class="callgraph">View Callgraph</a>');
print("</div>");

print("<div id=\"clear\"></div>");

print('<div class="colone">');
//   cookie diff data from array position 0
if (!isset($GLOBALS['_xhprof']['serializer']) || strtolower($GLOBALS['_xhprof']['serializer']) == 'php') {
	$cookieArr0 = unserialize($xhprof_runs_impl->run_details[0]['cookie']);
	$cookieArr1 = unserialize($xhprof_runs_impl->run_details[1]['cookie']);
	$getArr0 = unserialize($xhprof_runs_impl->run_details[0]['get']);
	$getArr1 = unserialize($xhprof_runs_impl->run_details[1]['get']);
	$postArr0 = unserialize($xhprof_runs_impl->run_details[0]['post']);
	$postArr1 = unserialize($xhprof_runs_impl->run_details[1]['post']);
} else {
	$cookieArr0 = json_decode($xhprof_runs_impl->run_details[0]['cookie'], TRUE);
	$cookieArr1 = json_decode($xhprof_runs_impl->run_details[1]['cookie'], TRUE);
	$getArr0 = json_decode($xhprof_runs_impl->run_details[0]['get'], TRUE);
	$getArr1 = json_decode($xhprof_runs_impl->run_details[1]['get'], TRUE);
	$postArr0 = json_decode($xhprof_runs_impl->run_details[0]['post'], TRUE);
	$postArr1 = json_decode($xhprof_runs_impl->run_details[1]['post'], TRUE);
}


print ('<div class="box-fix-small">');
print '<table class="box-tables-small">';
print "<thead>";
print "<tr><th>Run One ID:\n$run1</th><th>Cookie Results</th></tr>";
print "</head>";
print "<tbody>";

foreach ($cookieArr0 as $key => $value) {
	echo "<tr>";

	if (isset($cookieArr1[$key]) && $cookieArr0[$key] == $cookieArr1[$key]) {
		$class = "normal";
	} else {
		$class = "different";
	}
	echo "<td>" . $key . "</td><td class=\"" . $class . "\">" . chunk_split($value) . "</td>";
	echo "</tr>";
}
print  "</tbody>";
print  "</table>";
print  "</div>";

//   get diff data from array position 0

// $getArr0 =  json_decode($xhprof_runs_impl->run_details[0]['get']);
print '<div class="box-fix-small-cl">';
print '<table class="box-tables-small">';
print "<thead>";
print "<tr><th>Run:$run1</th><th>Get Results</th></tr>";
print "</head>";
print "<tbody>";

foreach ($getArr0 as $key => $value) {
	echo "<tr>";

	if (isset($getArr1[$key]) && ($getArr0[$key] == $getArr1[$key])) {
		$class = "normal";
	} else {
		$class = "different";
	}
	if (is_array($value)) {
		$value = implode(", ", $value);
	}
	echo "<td>" . $key . "</td><td class=\"" . $class . "\">" . chunk_split($value) . "</td>";
	echo "</tr>";
}
print  "</tbody>";
print  "</table>";
print  "</div>";

//   post diff data from array position 0
// $postArr0 =  json_decode($xhprof_runs_impl->run_details[0]['post']);
print '<div class="box-fix-small-cl">';
print '<table class="box-tables-small">';
print "<thead>";
print "<tr><th>Run:$run1</th><th>Post Results</th></tr>";
print "</head>";
print "<tbody>";

foreach ($postArr0 as $key => $value) {
	echo "<tr>";
	if (isset($postArr1[$key]) && $postArr0[$key] == $postArr1[$key]) {
		$class = "normal";
	} else {
		$class = "different";
	}
	echo "<td>" . $key . "</td><td class=\"" . $class . "\">" . chunk_split($value) . "</td>";
	echo "</tr>";
}
print  "</tbody>";
print  "</table>";
print  "</div>";

print('</div>');

print('<div class="coltwo">');
print('<div id="diff-summary">');
print('<table class="diff-box">');
print("<thead>");
print('<tr>');
print("<th></th>");
foreach($runs as $key => $runId) {
	$href = "$base_path/?" .
		http_build_query(xhprof_array_set($url_params, 'run', $runId));
	print("<th $vwbar>" . ucfirst($key) . " ID: " . xhprof_render_link("$runId", $href) . "</th>");
}
print("<th $vwbar>Diff</th>");
print("<th $vwbar>Diff%</th>");
print('</tr>');
print("</thead>");
print "<tbody>";
if ($display_calls) {
	print('<tr>');
	print("<td>Number of Function Calls</td>");
	print_td_num($totals_1["ct"], $format_cbk["ct"]);
	print_td_num($totals_2["ct"], $format_cbk["ct"]);
	print_td_num($totals_2["ct"] - $totals_1["ct"], $format_cbk["ct"], TRUE);
	print_td_pct($totals_2["ct"] - $totals_1["ct"], $totals_1["ct"], TRUE);
	print('</tr>');
}

foreach ($metrics as $metric) {
	$m = $metric;
	print('<tr>');
	print("<td>" . str_replace("<br>", " ", $descriptions[$m]) . "</td>");
	print_td_num($totals_1[$m], $format_cbk[$m]);
	print_td_num($totals_2[$m], $format_cbk[$m]);
	print_td_num($totals_2[$m] - $totals_1[$m], $format_cbk[$m], TRUE);
	print_td_pct($totals_2[$m] - $totals_1[$m], $totals_1[$m], TRUE);
	print('<tr>');
}
print "</tbody>";
print('</table>');
print('</div>');


print('</div>');


print('<div class="colthree">');
print '<div class="box-fix-small">';
print '<table class="box-tables-small">';
print "<thead>";
print "<tr><th>Run Two ID:\n$run2</th><th>Cookie Results</th></tr>";
print "</head>";
print "<tbody>";
//  cookie diff data from array position 1
//$cookieArr1 =  json_decode($xhprof_runs_impl->run_details[1]['cookie']);

foreach ($cookieArr1 as $key => $value) {
	echo "<tr>";

	if (isset($cookieArr0[$key]) && ($cookieArr1[$key] == $cookieArr0[$key])) {
		$class = "normal";
	} else {
		$class = "different";
	}
	echo "<td>" . $key . "</td><td class=\"" . $class . "\">" . chunk_split($value) . "</td>";
	echo "</tr>";
}
print  "</tbody>";
print  "</table>";
print  "</div>";


print '<div class="box-fix-small-cl">';
print '<table class="box-tables-small">';
print "<thead>";
print "<tr><th>Run:$run2</th><th>Get Results</th></tr>";
print "</head>";
print "<tbody>";
//   get diff data from array position 1
//  $getArr1 =  json_decode($xhprof_runs_impl->run_details[1]['get']);

foreach ($getArr1 as $key => $value) {
	echo "<tr>";

	if (isset($getArr0[$key]) && ($getArr1[$key] == $getArr0[$key])) {
		$class = "normal";
	} else {
		$class = "different";
	}
	if (is_array($value)) {
		$value = implode(", ", $value);
	}
	echo "<td>" . $key . "</td><td class=\"" . $class . "\">" . chunk_split($value) . "</td>";
	echo "</tr>";
}
print  "</tbody>";
print  "</table>";
print  "</div>";


print '<div class="box-fix-small-cl">';
print '<table class="box-tables-small">';
print "<thead>";
print "<tr><th>Run:$run2</th><th>Post Results</th></tr>";
print "</head>";
print "<tbody>";
//   post diff data from array position 1
// $postArr1 =  json_decode($xhprof_runs_impl->run_details[1]['post']);

foreach ($postArr1 as $key => $value) {
	echo "<tr>";

	if ($postArr1[$key] == $postArr0[$key]) {
		$class = "normal";
	} else {
		$class = "different";
	}
	echo "<td>" . $key . "</td><td class=\"" . $class . "\">" . chunk_split($value) . "</td>";
	echo "</tr>";
}
?>
</tbody>
</table>
</div>
</div>
</div>
