<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
	<title>XHGui: Hierarchical Profiler Report</title>

	<link href='css/normalize.css' rel='stylesheet' type='text/css'/>
	<link href='css/jquery.dataTables.css' rel='stylesheet' type='text/css'/>
	<link
		href='<?php echo ($_xhprof['styleSheet']) ? $_xhprof['styleSheet'] : 'css/xhprof.css' ?>'
		rel='stylesheet' type='text/css'/>
	<link href='third-party/jquery/jquery.autocomplete.css' rel='stylesheet'
	      type='text/css'/>
	<script src='third-party/jquery/jquery-2.0.3.min.js'
	        type="text/javascript"></script>
	<script src='third-party/highcharts/highcharts.js'
	        type="text/javascript"></script>
	<?php
	if (isset($_xh_header)) {
		echo $_xh_header;
	}
	?>
</head>
<body>
<div class="dash-header">
	<div class="search">
		<form name="simple_bar" method="get" action="">
			Search: <input type="text" name="run" size="25"/>
			<input type="submit" value="Go" class="form-button"/>
		</form>
	</div>
	<div class="search">
		<form name="simple_bar" id="domainFilter" method="get" action="">
			Filter Domain:
			<select name="domain_filter" id="domainFilterDomain">
				<?php
				foreach ($domainFilterOptions as $server) {
					if ($server === $domainFilter) {
						echo "<option value=\"{$server}\" selected=\"selected\">$server</option>\n";
					} else {
						echo "<option value=\"{$server}\">$server</option>\n";
					}
				}
				?>
			</select>
			<input type="submit" value="Apply" class="form-button"/>
		</form>
	</div>
	<div class="search">
		<form name="simple_bar" id="serverFilter" method="get" action="">
			Filter Server:
			<select name="server_filter" id="serverFilterServer">
				<?php
				foreach ($serverFilterOptions as $server) {
					if ($server === $serverFilter) {
						echo "<option value=\"{$server}\" selected=\"selected\">$server</option>\n";
					} else {
						echo "<option value=\"{$server}\">$server</option>\n";
					}
				}
				?>
			</select>
			<input type="submit" value="Apply" class="form-button"/>
		</form>
	</div>
	<div class="link-options">
		Last <a href="?last=25">25</a> <a href="?last=50">50</a> Runs |
		Hardest Hit <a href="?hit=50&amp;days=1">Today</a> <a
			href="?hit=50&amp;days=7">Past Week</a> |
		Most Expensive <a href="?getruns=cpu&amp;days=1">Today</a> <a
			href="?getruns=cpu&amp;days=7">Past Week</a> |
		Most Ram <a href="?getruns=pmu&amp;days=1">Today</a> <a
			href="?getruns=pmu&amp;days=7">Past Week</a> |
		Longest Running <a href="?getruns=wt&amp;days=1">Today</a> <a
			href="?getruns=wt&amp;days=7">Past Week</a>
	</div>
	<h1 class="xh-title"><a href="?">XH GUI</a></h1>
</div>