<script type="text/javascript">
	/**
	 * Format an integer as a time value
	 *
	 * @param {String} time The value to format.
	 * @param {Number} decimals The amount of decimals
	 *
	 * @return string
	 */
	function printSeconds(time, decimals) {
	   decimals = typeof decimals !== 'undefined' ? decimals : 2;
		time = time * 1000;
		var prefix = '',
			suffix = 'μs';
		if (time < 0) {
			time = Math.abs(time);
			prefix = '-';
		}

		if (time == 0) {
			suffix = '';
		}

		if (time > 1000) {
			time = time / 1000;
			suffix = 'ms';
		}

		if (time > 1000) {
			time = time / 1000;
			suffix = ' s';
		}

		if (time > 60 && suffix == ' s') {
			time = time / 60;
			suffix = 'min!';
		}

		return prefix + Highcharts.numberFormat(time, decimals) + ' ' + suffix;
	}
	
	Highcharts.setOptions({
		colors: ['#4572A7', '#AA4643', '#89A54E', '#80699B', '#3D96AE', '#DB843D', '#92A8CD', '#A47D7C', '#B5CA92', '#EAFEBB', '#FEB4B1', '#2B6979', '#E9D6FE', '#FECDA3', '#FED980'],
		chart: {
			height: '300',
			events: {
				load: function() {
					var label = this['renderer']['label']('Clicking on a label (except Loading and Other) will show the callgraph for that function.')
						.css({
							width: '200px',
							color: '#777'
						})
						.attr({
							padding: 3
						})
						.add();

					label.align(Highcharts.extend(['label']['getBBox()'], {
						'align': 'right',
						'x': -210, // offset
						'verticalAlign': 'top',
						'y': 10 // offset
					}), null, 'spacingBox');
				}
			}
		},
		credits: {
			enabled: false
		},
		lang: {
			thousandsSep: '<?php echo $_xhprof['thousandsSeparator'] ?>',
			decimalPoint: '<?php echo $_xhprof['decimalSeparator'] ?>'
		},
		legend: {
			enabled: false,
			align: 'left',
			layout: 'vertical',
			verticalAlign: 'middle',
			labelFormatter: function() {
				return this.name + " (" + Highcharts.numberFormat(this.percentage) + "%)";
			}
		},
		plotOptions: {
			pie: {
				allowPointSelect: true,
				cursor: 'pointer',
				showInLegend: true,
				dataLabels: {
					enabled: true,
					color: '#777'
				}
			}
		},
		tooltip: {
			formatter: function() {
				return '<b>' + this.point.name + '</b><br/>' +
					'Wall: ' + printSeconds(this.point.wall.toString()) + '<br/>' +
					'CPU: ' + printSeconds(this.point.cpu.toString()) + '<br/>' +
					'Calls: ' + Highcharts.numberFormat(this.point.calls, 0);
			}
		}
	});
	var exclusiveWallTimeChart = new Highcharts.Chart({
		chart: {
			renderTo: 'exclusiveWallTimeChart'
		},
		title: {
			text: 'Expensive Calls by Exclusive Wall Time'
		},
		plotOptions: {
			pie: {
				dataLabels: {
					formatter: function() {
						if (this.point.name == 'Loading' || this.point.name == 'Other') {
							return this.point.name + ': ' + Highcharts.numberFormat(this.percentage) + '%';
						}
						return  '<a href="<?php echo $callGraphUrl . $run2['id']; ?>&func=' + encodeURIComponent(this.point.name) + '">' + this.point.name + '</a>: ' + Highcharts.numberFormat(this.percentage) + '%';
					}
				}
			}
		},
		series: [
			{
				type: 'pie',
				name: 'Expensive Calls by Exclusive Wall Time',
				data: [
					<?php
							$iterations = 0;
							$other = 0;
							$otherCpu = 0;
							$otherWall = 0;
							$otherCalls = 0;
							foreach($data_copy as $dataPoint) {
								 if (++$iterations > 18) {
									  $other+= $dataPoint['excl_wt'];
									  $otherCpu+= $dataPoint['excl_cpu'];
									  $otherWall+= $dataPoint['excl_wt'];
									  $otherCalls+= $dataPoint['ct'];
								 } else {
									  echo "{name: '" . str_replace('\\', '\\\\', $dataPoint['fn']) . "', y: {$dataPoint['excl_wt']}, cpu: {$dataPoint['excl_cpu']}, wall: {$dataPoint['excl_wt']}, calls: {$dataPoint['ct']}},\n";
								 }
							}
							echo "{name: 'Other',y: $other, cpu: $otherCpu, wall: $otherWall, calls: $otherCalls}";
					  ?>
				]
			}
		]
	});
	var exclusiveCpuTimeChart = new Highcharts.Chart({
		chart: {
			renderTo: 'exclusiveCpuTimeChart'
		},
		title: {
			text: 'Expensive Calls by Exclusive CPU Time'
		},
		plotOptions: {
			pie: {
				dataLabels: {
					formatter: function() {
						if (this.point.name == 'Loading' || this.point.name == 'Other') {
							return this.point.name + ': ' + Highcharts.numberFormat(this.percentage) + '%';
						}
						return  '<a href="<?php echo $callGraphUrl . $run2['id']; ?>&func=' + encodeURIComponent(this.point.name) + '">' + this.point.name + '</a>: ' + Highcharts.numberFormat(this.percentage) + '%';
					}
				}
			}
		},
		series: [
			{
				type: 'pie',
				name: 'Expensive Calls by Exclusive CPU Time',
				data: [
					<?php
							$iterations = 0;
							$other = 0;
							$otherCpu = 0;
							$otherWall = 0;
							$otherCalls = 0;
							foreach($data_cpu as $dataPoint) {
								 if (++$iterations > 18) {
									  $other+= $dataPoint['excl_cpu'];
									  $otherCpu+= $dataPoint['excl_cpu'];
									  $otherWall+= $dataPoint['excl_wt'];
									  $otherCalls+= $dataPoint['ct'];
								 } else {
									  echo "{name: '" . str_replace('\\', '\\\\', $dataPoint['fn']) . "', y: {$dataPoint['excl_cpu']}, cpu: {$dataPoint['excl_cpu']}, wall: {$dataPoint['excl_wt']}, calls: {$dataPoint['ct']}},\n";
								 }
							}
							echo "{name: 'Other',y: $other, cpu: $otherCpu, wall: $otherWall, calls: $otherCalls}";
					  ?>
				]
			}
		]
	});
	var mostCalledMethodsChart = new Highcharts.Chart({
		chart: {
			renderTo: 'mostCalledMethodsChart'
		},
		title: {
			text: 'Most called methods'
		},
		plotOptions: {
			pie: {
				dataLabels: {
					formatter: function() {
						if (this.point.name == 'Loading' || this.point.name == 'Other') {
							return this.point.name + ': ' + Highcharts.numberFormat(this.percentage) + '%';
						}
						return  '<a href="<?php echo $callGraphUrl . $run2['id']; ?>&func=' + encodeURIComponent(this.point.name) + '">' + this.point.name + '</a>: ' + Highcharts.numberFormat(this.percentage) + '%';
					}
				}
			}
		},
		series: [
			{
				type: 'pie',
				name: 'Most called methods',
				data: [
					<?php
							$iterations = 0;
							$other = 0;
							$otherCpu = 0;
							$otherWall = 0;
							$otherCalls = 0;
							foreach($data_calls as $dataPoint)
							{
								 if (++$iterations > 18) {
									  $other+= $dataPoint['ct'];
									  $otherCpu+= $dataPoint['excl_cpu'];
									  $otherWall+= $dataPoint['excl_wt'];
									  $otherCalls+= $dataPoint['ct'];
								 } else {
									  echo "{name: '" . str_replace('\\', '\\\\', $dataPoint['fn']) . "', y: {$dataPoint['ct']}, cpu: {$dataPoint['excl_cpu']}, wall: {$dataPoint['excl_wt']}, calls: {$dataPoint['ct']}},\n";
								 }
							}
							echo "{name: 'Other',y: $other, cpu: $otherCpu, wall: $otherWall, calls: $otherCalls}";
					  ?>
				]
			}
		]
	});
</script>
