<script type="text/javascript">
	Highcharts.setOptions({
		colors: ['#4572A7', '#AA4643', '#89A54E', '#80699B', '#3D96AE', '#DB843D', '#92A8CD', '#A47D7C', '#B5CA92', '#EAFEBB', '#FEB4B1', '#2B6979', '#E9D6FE', '#FECDA3', '#FED980'],
		credits: {
			enabled: false
		},
		lang: {
			thousandsSep: '<?php echo $_xhprof['thousandsSeparator'] ?>',
			decimalPoint: '<?php echo $_xhprof['decimalSeparator'] ?>'
		}
	});
	var exclusiveWallTimeChart = new Highcharts.Chart({
		chart: {
			renderTo: 'exclusiveWallTimeChart',
			height: '300'
		},
		title: {
			text: 'Expensive Calls by Exclusive Wall Time'
		},
		tooltip: {
			formatter: function() {
				return '<b>' + this.point.name + '</b>: ' + this.y.toString().replace(/\B(?=(\d{3})+(?!\d))/g, "<?php echo $_xhprof['thousandsSeparator'] ?>") + 'μs';
			}
		},
		plotOptions: {
			pie: {
				allowPointSelect: true,
				cursor: 'pointer',
				showInLegend: true,
				dataLabels: {
					enabled: true,
					color: '#777',
					formatter: function() {
						return  '<a href="<?php echo $callGraphUrl . $run2['id']; ?>&func=' + this.point.name + '">' + this.point.name + '</a>: ' + Highcharts.numberFormat(this.percentage) + '%';
					}
				}
			}
		},
		legend: {
			enabled: false,
			align: 'left',
			layout: 'vertical',
			verticalAlign: 'middle',
			labelFormatter: function() {
				return this.name + " (" + Highcharts.numberFormat(this.percentage) + "%)";
			}
		},
		series: [
			{
				type: 'pie',
				name: 'Expensive Calls by Exclusive Wall Time',
				data: [
					<?php
							$iterations = 0;
							$other = 0;
							foreach($data_copy as $dataPoint)
							{
								 if (++$iterations > 14)
								 {
									  $other+= $dataPoint['excl_wt'];
								 }else
								 {
									  echo "['{$dataPoint['fn']}', {$dataPoint['excl_wt']}],\n";
								 }
							}
							echo "['Other', $other]";
					  ?>
				]
			}
		]
	});
	var exclusiveCpuTimeChart = new Highcharts.Chart({
		chart: {
			renderTo: 'exclusiveCpuTimeChart',
			height: '300'
		},
		title: {
			text: 'Expensive Calls by Exclusive CPU Time'
		},
		tooltip: {
			formatter: function() {
				return '<b>' + this.point.name + '</b>: ' + this.y.toString().replace(/\B(?=(\d{3})+(?!\d))/g, "<?php echo $_xhprof['thousandsSeparator'] ?>") + 'μs';
			}
		},
		plotOptions: {
			pie: {
				allowPointSelect: true,
				cursor: 'pointer',
				showInLegend: true,
				dataLabels: {
					enabled: true,
					color: '#777',
					formatter: function() {
						return  '<a href="<?php echo $callGraphUrl . $run2['id']; ?>&func=' + this.point.name + '">' + this.point.name + '</a>: ' + Highcharts.numberFormat(this.percentage) + '%';
					}
				}
			}
		},
		legend: {
			enabled: false,
			align: 'left',
			layout: 'vertical',
			verticalAlign: 'middle',
			labelFormatter: function() {
				return this.name + " (" + Highcharts.numberFormat(this.percentage) + "%)";
			}
		},
		series: [
			{
				type: 'pie',
				name: 'Expensive Calls by Exclusive CPU Time',
				data: [
					<?php
							$iterations = 0;
							$other = 0;
							foreach($data_cpu as $dataPoint)
							{
								 if (++$iterations > 14)
								 {
									  $other+= $dataPoint['excl_cpu'];
								 }else
								 {
									  echo "['{$dataPoint['fn']}', {$dataPoint['excl_cpu']}],\n";
								 }
							}
							echo "['Other', $other]";
					  ?>
				]
			}
		]
	});
	var mostCalledMethodsChart = new Highcharts.Chart({
		chart: {
			renderTo: 'mostCalledMethodsChart',
			height: '300'
		},
		title: {
			text: 'Most called methods'
		},
		tooltip: {
			formatter: function() {
				return '<b>' + this.point.name + '</b>: ' + this.y + ' calls';
			}
		},
		plotOptions: {
			pie: {
				allowPointSelect: true,
				cursor: 'pointer',
				showInLegend: true,
				dataLabels: {
					enabled: true,
					color: '#777',
					formatter: function() {
						return  '<a href="<?php echo $callGraphUrl . $run2['id']; ?>&func=' + this.point.name + '">' + this.point.name + '</a>: ' + Highcharts.numberFormat(this.percentage) + '%';
					}
				}
			}
		},
		legend: {
			enabled: false,
			align: 'left',
			layout: 'vertical',
			verticalAlign: 'middle',
			labelFormatter: function() {
				return this.name + " (" + Highcharts.numberFormat(this.percentage) + "%)";
			}
		},
		series: [
			{
				type: 'pie',
				name: 'Most called methods',
				data: [
					<?php
							$iterations = 0;
							$other = 0;
							foreach($data_calls as $dataPoint)
							{
								 if (++$iterations > 14)
								 {
									  $other+= $dataPoint['ct'];
								 }else
								 {
									  echo "['{$dataPoint['fn']}', {$dataPoint['ct']}],\n";
								 }
							}
							echo "['Other', $other]";
					  ?>
				]
			}
		]
	});
</script>
