<table id="box-table-a" class="tablesorter" summary="Stats">
	<thead>
	<tr>
		<th>Group</th>
		<th>Function</th>
		<th>Call Count</th>
		<th title="elapsed time in ms: if you perform a network call, that’s the CPU time to call the service and parse the response, plus the time spent waiting for the response itself and other resources">Wall Time</th>
		<th title="CPU time in both kernel and user space">CPU Time</th>
		<th title="Memory Usage">Memory</th>
		<th title="Peak Memory Usage">Peak Memory</th>
		<th title="Wall Time for this function only">Excl. Wall</th>
		<th title="CPU Time for this function only">Excl. CPU</th>
		<th title="Memory Usage for this function only">Excl. Memory</th>
		<th title="Peak Memory Usage for this function only">Excl. Peak Memory</th>
	</tr>
	</thead>
	<tbody>
	<?php
	foreach ($flat_data as $element) {
		if (isset($element['group'])) {
			$color = $function_color[$element['group']];
		} elseif (isset($function_color[$element['fn']])) {
			$color = $function_color[$element['fn']];
		} else {
			$color = 'inherit';
		}
		?>

		<tr>
			<td style="background-color: <?php echo $color; ?>;">
				<span style="display: none"><?php echo $color; ?></span>&nbsp;</td>
			<td class="function" data-sort-value="<?php echo isset($element['fn']) ? $element['fn'] : ''; ?>">
				<a href="index.php?run=<?php echo $run1; ?>&amp;symbol=<?php echo urlencode($element['fn']); ?>"><?php echo htmlentities($element['fn'], ENT_QUOTES, 'UTF-8'); ?></a>
			</td>
			<td class="callCount" data-sort-value="<?php echo isset($element['ct']) ? $element['ct'] : ''; ?>"><?php echo isset($element['ct']) ? $element['ct'] : ''; ?></td>
			<td class="wallTime" data-sort-value="<?php echo isset($element['wt']) ? $element['wt'] : ''; ?>"><?php echo isset($element['wt']) ? printSeconds($element['wt']) : ''; ?></td>
			<td class="cpuTime"data-sort-value="<?php echo isset($element['cpu']) ? $element['cpu'] : ''; ?>"><?php echo isset($element['cpu']) ? printSeconds($element['cpu']) : ''; ?></td>
			<td class="memoryUsage" data-sort-value="<?php echo isset($element['mu']) ? $element['mu'] : ''; ?>"><?php if (isset($element['mu'])) {
					if ($element['mu'] < 0) {
						echo '-';
					}
					echo printBytes(abs($element['mu']));
				} else {
					echo '';
				} ?></td>
			<td class="peakMemoryUsage" data-sort-value="<?php echo isset($element['pmu']) ? $element['pmu'] : ''; ?>"><?php echo isset($element['pmu']) ? printBytes($element['pmu']) : ''; ?></td>
			<td class="wallTime" data-sort-value="<?php echo isset($element['excl_wt']) ? $element['excl_wt'] : ''; ?>"><?php echo isset($element['excl_wt']) ? printSeconds($element['excl_wt']) : ''; ?></td>
			<td class="cpuTime" data-sort-value="<?php echo isset($element['excl_cpu']) ? $element['excl_cpu'] : ''; ?>"><?php echo isset($element['excl_cpu']) ? printSeconds($element['excl_cpu']) : ''; ?></td>
			<td class="memoryUsage" data-sort-value="<?php echo isset($element['excl_mu']) ? $element['excl_mu'] : ''; ?>"><?php if (isset($element['excl_mu'])) {
					if ($element['excl_mu'] < 0) {
						echo '-';
					}
					echo printBytes(abs($element['excl_mu']));
				} else {
					echo '';
				} ?></td>
			<td class="peakMemoryUsage" data-sort-value="<?php echo isset($element['excl_pmu']) ? $element['excl_pmu'] : ''; ?>"><?php echo isset($element['excl_pmu']) ? printBytes($element['excl_pmu']) : ''; ?></td>
		</tr>
	<?php
	}
	?>
	</tbody>
</table>
